### ISSUE TITLE
Unable to build with latest SDKs

### ISSUE THREAD

**Issue by mattyg** [voxeet/voxeet-sdk-android-gettingstarted#6]
When attempting to build with voxeet SDK version 2.4.2, or 3.0.0-BETA2010191520, the build fails with:

"Cannot find symbol class MediaStreamType" referring to the line: "import com.voxeet.android.media.MediaStreamType;"

**Comment by FabienLavocat** [comment]
Hi @mattyg, in the most recent version of our SDK, the `MediaStreamType` class has been moved to a different package. You need to replace the import statement by:

```
import com.voxeet.android.media.stream.MediaStreamType;
```

I prepared a fork of this project and will create the Pull Request soon.
https://github.com/FabienLavocat/voxeet-sdk-android-gettingstarted

Thanks,
Fabien
